[package]
name = "rsdsl_he_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnet = "2.7.1"
serde = { version = "1.0", features = ["derive"] }
